---
title: "Funding Disparities"
description: |
 This page focuses on answering the question of **Resource allocation** where we investigate potential disparities in funding for syllabus books across various regions, identifying any imbalances in resource allocation.
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



```{r}
library(tidyverse)
setwd("D:\\setebe\\Data science\\2024\\Tanzania-Education")

# Read the CSV file
ed <- read.csv("Education.csv")
attach(ed)
```





```{r}
# Grouped bar plot for science and arts categories with close grouping

# Define the columns for the different categories
science_books <- c("agriculture_form3Books", "bmath_form3Books", "biology_form3Books",
                   "chemistry_form3Books", "physics_form3Books")
arts_books <- c("kiswahili_form3Books", "history_form3Books", "geography_form3Books",
                "english_form3Books", "commerce_form3Books", "civics_form3Books")
science_students <- c("Agriculture_form3Students", "basicMath_form3Students", 
                      "biology_form3Students", "chemistry_form3Students", 
                      "physics_form3Students")
arts_students <- c("kiswahili_form3Students", "history_form3Students", 
                   "geography_form3Students", "english_form3Students", 
                   "commerce_form3Students", "civics_form3Students")

# Define the population ranks for regions
population_ranks <- c("Dar es Salaam", "Mwanza", "Tabora", "Morogoro", "Dodoma",
                      "Kagera", "Geita", "Tanga", "Kigoma", "Mara",
                      "Arusha", "Mbeya", "Shinyanga", "Simiyu", "Pwani",
                      "Singida", "Manyara", "Kilimanjaro", "Ruvuma", "Mtwara",
                      "Rukwa", "Songwe", "Lindi", "Iringa", "Katavi", "Njombe")

# Filter data to include only the regions ranked 1 to 5 by population rank
top1_to_5_regions <- population_ranks[1:5]
ed_top1_to_5 <- ed %>% filter(region %in% top1_to_5_regions)

# Sum the columns for science and arts books and students per region
data_summary <- ed_top1_to_5 %>%
  group_by(region) %>%
  summarise(ScienceBooks = sum(across(all_of(science_books)), na.rm = TRUE),
            ArtsBooks = sum(across(all_of(arts_books)), na.rm = TRUE),
            ScienceStudents = sum(across(all_of(science_students)), na.rm = TRUE),
            ArtsStudents = sum(across(all_of(arts_students)), na.rm = TRUE))

# Prepare data for plotting with adjusted category order
data_melted <- data_summary %>%
  pivot_longer(cols = c("ScienceBooks", "ScienceStudents", "ArtsBooks", "ArtsStudents"), 
               names_to = "Category", values_to = "Count") %>%
  mutate(Category = factor(Category, 
                           levels = c("ScienceBooks", "ScienceStudents", "ArtsBooks", "ArtsStudents"),
                           labels = c("Science Books", "Science Students", "Arts Books", "Arts Students")))

# Plot the data with custom colors and close grouping
ggplot(data_melted, aes(x = region, y = Count, fill = Category)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.8)) +
  scale_fill_manual(values = c("Science Students" = "#D1CFE2", 
                               "Science Books" = "#9CADCE", 
                               "Arts Students" = "#7EC4CF", 
                               "Arts Books" = "#5EBDDA")) +
  labs(title = "Comparison of Science and Arts Students and Books by Region",
       subtitle = "Population Rank 1-5",
       caption = "Form three Ordinary Secondary Education data of 2021",
       x = "Region",
       y = "Total Count",
       fill = "Category") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 360, hjust = 0.5, vjust = 0.5))


```




```{r}
# Grouped bar plot for science and arts categories with close grouping for population ranks 6-10

# Define the columns for the different categories
science_books <- c("agriculture_form3Books", "bmath_form3Books", "biology_form3Books",
                   "chemistry_form3Books", "physics_form3Books")
arts_books <- c("kiswahili_form3Books", "history_form3Books", "geography_form3Books",
                "english_form3Books", "commerce_form3Books", "civics_form3Books")
science_students <- c("Agriculture_form3Students", "basicMath_form3Students", 
                      "biology_form3Students", "chemistry_form3Students", 
                      "physics_form3Students")
arts_students <- c("kiswahili_form3Students", "history_form3Students", 
                   "geography_form3Students", "english_form3Students", 
                   "commerce_form3Students", "civics_form3Students")

# Define the population ranks for regions
population_ranks <- c("Dar es Salaam", "Mwanza", "Tabora", "Morogoro", "Dodoma",
                      "Kagera", "Geita", "Tanga", "Kigoma", "Mara",
                      "Arusha", "Mbeya", "Shinyanga", "Simiyu", "Pwani",
                      "Singida", "Manyara", "Kilimanjaro", "Ruvuma", "Mtwara",
                      "Rukwa", "Songwe", "Lindi", "Iringa", "Katavi", "Njombe")

# Filter data to include only the regions ranked 6 to 10 by population rank
top6_to_10_regions <- population_ranks[6:10]
ed_top6_to_10 <- ed %>% filter(region %in% top6_to_10_regions)

# Sum the columns for science and arts books and students per region
data_summary_6_to_10 <- ed_top6_to_10 %>%
  group_by(region) %>%
  summarise(ScienceBooks = sum(across(all_of(science_books)), na.rm = TRUE),
            ArtsBooks = sum(across(all_of(arts_books)), na.rm = TRUE),
            ScienceStudents = sum(across(all_of(science_students)), na.rm = TRUE),
            ArtsStudents = sum(across(all_of(arts_students)), na.rm = TRUE))

# Prepare data for plotting with adjusted category order
data_melted_6_to_10 <- data_summary_6_to_10 %>%
  pivot_longer(cols = c("ScienceBooks", "ScienceStudents", "ArtsBooks", "ArtsStudents"), 
               names_to = "Category", values_to = "Count") %>%
  mutate(Category = factor(Category, 
                           levels = c("ScienceBooks", "ScienceStudents", "ArtsBooks", "ArtsStudents"),
                           labels = c("Science Books", "Science Students", "Arts Books", "Arts Students")))

# Plot the data with custom colors and close grouping
ggplot(data_melted_6_to_10, aes(x = region, y = Count, fill = Category)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.8)) +
  scale_fill_manual(values = c("Science Students" = "#D1CFE2", 
                               "Science Books" = "#9CADCE", 
                               "Arts Students" = "#7EC4CF", 
                               "Arts Books" = "#5EBDDA")) +
  labs(title = "Comparison of Science and Arts Students and Books by Region",
       subtitle = "Population Rank 6-10",
       caption = "Form three Ordinary Secondary Education data of 2021",
       x = "Region",
       y = "Total Count",
       fill = "Category") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 360, hjust = 0.5, vjust = 0.5))
```



```{r}
# Grouped bar plot for science and arts categories with close grouping for population ranks 11-15

# Define the columns for the different categories
science_books <- c("agriculture_form3Books", "bmath_form3Books", "biology_form3Books",
                   "chemistry_form3Books", "physics_form3Books")
arts_books <- c("kiswahili_form3Books", "history_form3Books", "geography_form3Books",
                "english_form3Books", "commerce_form3Books", "civics_form3Books")
science_students <- c("Agriculture_form3Students", "basicMath_form3Students", 
                      "biology_form3Students", "chemistry_form3Students", 
                      "physics_form3Students")
arts_students <- c("kiswahili_form3Students", "history_form3Students", 
                   "geography_form3Students", "english_form3Students", 
                   "commerce_form3Students", "civics_form3Students")

# Define the population ranks for regions
population_ranks <- c("Dar es Salaam", "Mwanza", "Tabora", "Morogoro", "Dodoma",
                      "Kagera", "Geita", "Tanga", "Kigoma", "Mara",
                      "Arusha", "Mbeya", "Shinyanga", "Simiyu", "Pwani",
                      "Singida", "Manyara", "Kilimanjaro", "Ruvuma", "Mtwara",
                      "Rukwa", "Songwe", "Lindi", "Iringa", "Katavi", "Njombe")

# Filter data to include only the regions ranked 11 to 15 by population rank
top11_to_15_regions <- population_ranks[11:15]
ed_top11_to_15 <- ed %>% filter(region %in% top11_to_15_regions)

# Sum the columns for science and arts books and students per region
data_summary_11_to_15 <- ed_top11_to_15 %>%
  group_by(region) %>%
  summarise(ScienceBooks = sum(across(all_of(science_books)), na.rm = TRUE),
            ArtsBooks = sum(across(all_of(arts_books)), na.rm = TRUE),
            ScienceStudents = sum(across(all_of(science_students)), na.rm = TRUE),
            ArtsStudents = sum(across(all_of(arts_students)), na.rm = TRUE))

# Prepare data for plotting with adjusted category order
data_melted_11_to_15 <- data_summary_11_to_15 %>%
  pivot_longer(cols = c("ScienceBooks", "ScienceStudents", "ArtsBooks", "ArtsStudents"), 
               names_to = "Category", values_to = "Count") %>%
  mutate(Category = factor(Category, 
                           levels = c("ScienceBooks", "ScienceStudents", "ArtsBooks", "ArtsStudents"),
                           labels = c("Science Books", "Science Students", "Arts Books", "Arts Students")))

# Plot the data with custom colors and close grouping
ggplot(data_melted_11_to_15, aes(x = region, y = Count, fill = Category)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.8)) +
  scale_fill_manual(values = c("Science Students" = "#D1CFE2", 
                               "Science Books" = "#9CADCE", 
                               "Arts Students" = "#7EC4CF", 
                               "Arts Books" = "#5EBDDA")) +
  labs(title = "Comparison of Science and Arts Students and Books by Region",
       subtitle = "Population Rank 11-15",
       caption = "Form three Ordinary Secondary Education data of 2021",
       x = "Region",
       y = "Total Count",
       fill = "Category") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 360, hjust = 0.5, vjust = 0.5))
```



```{r}
# Grouped bar plot for science and arts categories with close grouping for population ranks 16-20

# Define the columns for the different categories
science_books <- c("agriculture_form3Books", "bmath_form3Books", "biology_form3Books",
                   "chemistry_form3Books", "physics_form3Books")
arts_books <- c("kiswahili_form3Books", "history_form3Books", "geography_form3Books",
                "english_form3Books", "commerce_form3Books", "civics_form3Books")
science_students <- c("Agriculture_form3Students", "basicMath_form3Students", 
                      "biology_form3Students", "chemistry_form3Students", 
                      "physics_form3Students")
arts_students <- c("kiswahili_form3Students", "history_form3Students", 
                   "geography_form3Students", "english_form3Students", 
                   "commerce_form3Students", "civics_form3Students")

# Define the population ranks for regions
population_ranks <- c("Dar es Salaam", "Mwanza", "Tabora", "Morogoro", "Dodoma",
                      "Kagera", "Geita", "Tanga", "Kigoma", "Mara",
                      "Arusha", "Mbeya", "Shinyanga", "Simiyu", "Pwani",
                      "Singida", "Manyara", "Kilimanjaro", "Ruvuma", "Mtwara",
                      "Rukwa", "Songwe", "Lindi", "Iringa", "Katavi", "Njombe")

# Filter data to include only the regions ranked 16 to 20 by population rank
top16_to_20_regions <- population_ranks[16:20]
ed_top16_to_20 <- ed %>% filter(region %in% top16_to_20_regions)

# Sum the columns for science and arts books and students per region
data_summary_16_to_20 <- ed_top16_to_20 %>%
  group_by(region) %>%
  summarise(ScienceBooks = sum(across(all_of(science_books)), na.rm = TRUE),
            ArtsBooks = sum(across(all_of(arts_books)), na.rm = TRUE),
            ScienceStudents = sum(across(all_of(science_students)), na.rm = TRUE),
            ArtsStudents = sum(across(all_of(arts_students)), na.rm = TRUE))

# Prepare data for plotting with adjusted category order
data_melted_16_to_20 <- data_summary_16_to_20 %>%
  pivot_longer(cols = c("ScienceBooks", "ScienceStudents", "ArtsBooks", "ArtsStudents"), 
               names_to = "Category", values_to = "Count") %>%
  mutate(Category = factor(Category, 
                           levels = c("ScienceBooks", "ScienceStudents", "ArtsBooks", "ArtsStudents"),
                           labels = c("Science Books", "Science Students", "Arts Books", "Arts Students")))

# Plot the data with custom colors and close grouping
ggplot(data_melted_16_to_20, aes(x = region, y = Count, fill = Category)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.8)) +
  scale_fill_manual(values = c("Science Students" = "#D1CFE2", 
                               "Science Books" = "#9CADCE", 
                               "Arts Students" = "#7EC4CF", 
                               "Arts Books" = "#5EBDDA")) +
  labs(title = "Comparison of Science and Arts Students and Books by Region",
       subtitle = "Population Rank 16-20",
       caption = "Form three Ordinary Secondary Education data of 2021",
       x = "Region",
       y = "Total Count",
       fill = "Category") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 360, hjust = 0.5, vjust = 0.5))
```

```{r}
# Grouped bar plot for science and arts categories with close grouping for population ranks 21-26

# Define the columns for the different categories
science_books <- c("agriculture_form3Books", "bmath_form3Books", "biology_form3Books",
                   "chemistry_form3Books", "physics_form3Books")
arts_books <- c("kiswahili_form3Books", "history_form3Books", "geography_form3Books",
                "english_form3Books", "commerce_form3Books", "civics_form3Books")
science_students <- c("Agriculture_form3Students", "basicMath_form3Students", 
                      "biology_form3Students", "chemistry_form3Students", 
                      "physics_form3Students")
arts_students <- c("kiswahili_form3Students", "history_form3Students", 
                   "geography_form3Students", "english_form3Students", 
                   "commerce_form3Students", "civics_form3Students")

# Define the population ranks for regions
population_ranks <- c("Dar es Salaam", "Mwanza", "Tabora", "Morogoro", "Dodoma",
                      "Kagera", "Geita", "Tanga", "Kigoma", "Mara",
                      "Arusha", "Mbeya", "Shinyanga", "Simiyu", "Pwani",
                      "Singida", "Manyara", "Kilimanjaro", "Ruvuma", "Mtwara",
                      "Rukwa", "Songwe", "Lindi", "Iringa", "Katavi", "Njombe")

# Filter data to include only the regions ranked 21 to 26 by population rank
top21_to_26_regions <- population_ranks[21:26]
ed_top21_to_26 <- ed %>% filter(region %in% top21_to_26_regions)

# Sum the columns for science and arts books and students per region
data_summary_21_to_26 <- ed_top21_to_26 %>%
  group_by(region) %>%
  summarise(ScienceBooks = sum(across(all_of(science_books)), na.rm = TRUE),
            ArtsBooks = sum(across(all_of(arts_books)), na.rm = TRUE),
            ScienceStudents = sum(across(all_of(science_students)), na.rm = TRUE),
            ArtsStudents = sum(across(all_of(arts_students)), na.rm = TRUE))

# Prepare data for plotting with adjusted category order
data_melted_21_to_26 <- data_summary_21_to_26 %>%
  pivot_longer(cols = c("ScienceBooks", "ScienceStudents", "ArtsBooks", "ArtsStudents"), 
               names_to = "Category", values_to = "Count") %>%
  mutate(Category = factor(Category, 
                           levels = c("ScienceBooks", "ScienceStudents", "ArtsBooks", "ArtsStudents"),
                           labels = c("Science Books", "Science Students", "Arts Books", "Arts Students")))

# Plot the data with custom colors and close grouping
ggplot(data_melted_21_to_26, aes(x = region, y = Count, fill = Category)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.8)) +
  scale_fill_manual(values = c("Science Students" = "#D1CFE2", 
                               "Science Books" = "#9CADCE", 
                               "Arts Students" = "#7EC4CF", 
                               "Arts Books" = "#5EBDDA")) +
  labs(title = "Comparison of Science and Arts Students and Books by Region",
       subtitle = "Population Rank 21-26",
       caption = "Form three Ordinary Secondary Education data of 2021",
       x = "Region",
       y = "Total Count",
       fill = "Category") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 360, hjust = 0.5, vjust = 0.5))
```

